### ISSUE TITLE
Great stuff

### ISSUE THREAD

**Issue by viebel** [srodrigo/lambda-calculus-in-clojure#1]
Great stuff Rodrigo.

I really love the fact that you used Clojure macros to adhere as much as possible to the Lambda Calculus original syntax and I really enjoyed your [blog post](https://codurance.com/2017/12/14/lambda-calculus-in-clojure/) .

I also tried to expose Lamda Calculus in terms of Clojure in a [blog post](http://blog.klipse.tech/lambda/2016/07/24/lambda-calculus-1.html).

I think it would be great if you use Klipse (I'm the author of Klipse!) to make your blog posts interactive.

**Comment by srodrigo** [comment]
Hi, thanks for reading my post!

I didn't know about Klipse. I'll have a look when I have a chance, sounds like a good idea.
