### ISSUE TITLE
Clojure functions vs lambda functions

### ISSUE THREAD

**Issue by viebel** [srodrigo/lambda-calculus-in-clojure#2]
`toInt`, `fromInt` etc... are not part of the Lambda Calculus.
They are clojure functions that help us (the humans) to visualize some Lambda Calculus.
Therefore, to me it makes more sense to write them as clojure Functions. Something like

```clojure
(defn toInt [f]
  ((f inc) 0))
```

**Comment by srodrigo** [comment]
That's a fair point. I agree that they are just helper functions. In this case, I decided to put them together with the numerals, as they are specific to them. The same reasoning for  `toBoolean`. But they could live in a separate file keeping the LC/Clojure separation in mind.

The reason for writing them using part of the Lambda Calculus syntax is to make it easier to relate both. But it's true that they could be written with plain Clojure syntax.

**Comment by viebel** [comment]
My point was that it might be confusing for the reader to see `toInt` written in LC. He might think that this is part of LC.
